name: id_scanner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2
  intl: ^0.19.0
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/schoolbg.jpg
    - assets/images/bantay-sinina-logo-nobg.png
  uses-material-design: true

